/**
 * Vercel Blob storage utilities.
 *
 * All resume data is stored in Vercel Blob under the `resume/` prefix.
 * The canonical resume document lives at RESUME_DATA_PATHNAME.
 *
 * Blob layout:
 *   resume/data.json                   — living-resume document
 *                                          (includes display_axes: Axis[] when present)
 *   resume/suggestions.json            — pending/approved/rejected suggestions
 *   resume/bullets/{YYYY-MM-DD}.json   — intermediate per-day bullet cache
 *   resume/keyword-cluster-axes.json   — persisted LLM keyword cluster axes
 *                                          (AxesDocument — separate from display_axes)
 *   resume/display-axes.json           — generated display axes as independent entities
 *                                          (DisplayAxesDocument — authoritative axis store)
 *
 * Environment variable required:
 *   BLOB_READ_WRITE_TOKEN — provisioned by Vercel Blob integration
 */

import { list, put, del } from "@vercel/blob";
import { migrateResumeDocument } from "./resumeMigration.mjs";

/** Pathname for the living-resume JSON document inside Vercel Blob. */
export const RESUME_DATA_PATHNAME = "resume/data.json";

/**
 * Blob pathname prefix for resume snapshots.
 * Individual snapshots are stored at `resume/snapshots/{ISO-timestamp}.json`.
 * The timestamp uses colons replaced with hyphens for filesystem-safe naming.
 */
export const SNAPSHOTS_PREFIX = "resume/snapshots/";

/** Pathname for the resume suggestions list inside Vercel Blob. */
export const SUGGESTIONS_PATHNAME = "resume/suggestions.json";

/**
 * Blob pathname prefix for per-day bullet cache files.
 * Individual files are stored at `resume/bullets/{YYYY-MM-DD}.json`.
 */
export const DAILY_BULLETS_PREFIX = "resume/bullets/";

/**
 * Blob pathname for the original PDF plain text extracted at bootstrap time.
 * Used by the reconstruction fallback to regenerate bullets without
 * requiring the user to re-upload the PDF.
 */
export const PDF_TEXT_PATHNAME = "resume/pdf-text.txt";

/**
 * Blob pathname for the original PDF binary uploaded at bootstrap time.
 * Stored as-is so that the raw file is preserved in Vercel Blob
 * (file-based → Blob 1:1 mapping).
 */
export const PDF_RAW_PATHNAME = "resume/resume.pdf";

/**
 * Blob pathname for the explicit reconstruction marker.
 * When this file exists, the next GET /api/resume (or POST /api/resume/rebuild)
 * will trigger a full reconstruction from original sources.
 */
export const RECONSTRUCTION_MARKER_PATHNAME = "resume/needs-reconstruction.json";

/**
 * Blob pathname for the keyword cluster axes document.
 * Stores the 5–6 thematic axes generated by LLM keyword clustering so that
 * subsequent classification calls can reuse the same axis set without
 * re-calling the LLM.
 */
export const KEYWORD_CLUSTER_AXES_PATHNAME = "resume/keyword-cluster-axes.json";

/**
 * Blob pathname for the display axes document.
 *
 * Stores the 2–4 career-narrative display axes generated by the LLM axis-
 * clustering pipeline as an independent entity, separate from the main resume
 * document.  Writing axes here lets GET /api/resume/axes avoid loading the
 * entire resume/data.json when axes are the only thing needed.
 *
 * Document shape (DisplayAxesDocument):
 *   {
 *     schemaVersion: 1,
 *     generatedAt: ISO string,
 *     axes: Axis[]    // { id, label, keywords[], _source }
 *   }
 */
export const DISPLAY_AXES_PATHNAME = "resume/display-axes.json";

/**
 * Blob pathname for the strength-keywords document.
 *
 * Stores the flat keyword list separately from the main resume document so that
 * keyword reads and writes do not require fetching or saving the entire resume.
 *
 * Document shape (StrengthKeywordsDocument):
 *   {
 *     schemaVersion: 1,
 *     updatedAt: ISO string,
 *     source: "bootstrap" | "user" | "system",
 *     keywords: string[]
 *   }
 */
export const STRENGTH_KEYWORDS_PATHNAME = "resume/strength-keywords.json";

/**
 * Blob pathname for the LinkedIn import data document.
 * Stores the structured ProfileData (experience, education, skills, certifications)
 * parsed from a LinkedIn PDF profile export or data export ZIP.
 *
 * LinkedIn is used ONLY during initial onboarding (one-shot).
 * After the resume is bootstrapped, this file is retained as a source
 * reference but is NOT re-read by the system during normal operation.
 *
 * Document shape:
 *   {
 *     schemaVersion: 1,
 *     importedAt: ISO string,
 *     source: "linkedin_pdf" | "linkedin_zip",
 *     data: ProfileData            — structured sections from the LinkedIn export
 *   }
 *
 * ProfileData shape:
 *   {
 *     name: string | null,
 *     headline: string | null,
 *     about: string | null,
 *     location: string | null,
 *     profileImageUrl: string | null,
 *     experience: { title, company, duration, description }[],
 *     education: { school, degree, field, years }[],
 *     skills: string[],
 *     certifications: { name, issuer, date }[]
 *   }
 */
export const LINKEDIN_IMPORT_PATHNAME = "resume/linkedin-import.json";

/**
 * Check whether the resume document exists in Vercel Blob.
 *
 * Uses `list()` with an exact-prefix filter so that no full URL is
 * required — the pathname alone is sufficient.
 *
 * @returns {Promise<{ exists: false } | { exists: true, url: string, uploadedAt: string, size: number }>}
 */
export async function checkResumeExists() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: RESUME_DATA_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === RESUME_DATA_PATHNAME);

  if (!match) {
    return { exists: false };
  }

  return {
    exists: true,
    url: match.url,
    uploadedAt: match.uploadedAt,
    size: match.size
  };
}

/**
 * Save (overwrite) the living-resume JSON document in Vercel Blob.
 *
 * Uses `put()` with `addRandomSuffix: false` and `allowOverwrite: true`
 * so that the canonical pathname `resume/data.json` is always stable.
 *
 * @param {object} data  Structured resume document (RESUME_SCHEMA_VERSION)
 * @returns {Promise<{ url: string }>}
 */
export async function saveResumeData(data) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const json = JSON.stringify(data, null, 2);

  const result = await put(RESUME_DATA_PATHNAME, json, {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Download and parse the living-resume JSON document from Vercel Blob.
 *
 * Returns `null` when no resume has been saved yet.
 *
 * @returns {Promise<object|null>}
 */
export async function readResumeData() {
  const status = await checkResumeExists();
  if (!status.exists) return null;

  const response = await fetch(status.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch resume data: ${response.status}`);
  }
  const raw = await response.json();
  // Ensure all items carry a valid _source provenance tag.
  // migrateResumeDocument is idempotent and returns the same reference when
  // no migration is needed, so this adds zero overhead on modern documents.
  return migrateResumeDocument(raw);
}

// ─── Suggestions storage ───────────────────────────────────────────────────

/**
 * Save (overwrite) the resume suggestions list in Vercel Blob.
 *
 * The suggestions document shape:
 *   {
 *     schemaVersion: 1,
 *     updatedAt: ISO string,
 *     suggestions: SuggestionItem[]
 *   }
 *
 * @param {object} data  Suggestions document
 * @returns {Promise<{ url: string }>}
 */
export async function saveSuggestionsData(data) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const json = JSON.stringify(data, null, 2);

  const result = await put(SUGGESTIONS_PATHNAME, json, {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Download and parse the resume suggestions from Vercel Blob.
 *
 * Returns a document with an empty `suggestions` array when none exist.
 *
 * @returns {Promise<{ schemaVersion: number, updatedAt: string, suggestions: object[] }>}
 */
export async function readSuggestionsData() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: SUGGESTIONS_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === SUGGESTIONS_PATHNAME);
  if (!match) {
    return { schemaVersion: 1, updatedAt: new Date().toISOString(), suggestions: [] };
  }

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch suggestions data: ${response.status}`);
  }
  return response.json();
}

// ─── Daily bullets cache storage ───────────────────────────────────────────────

/**
 * Derive the Vercel Blob pathname for a given work-log date's bullet cache.
 *
 * @param {string} date  ISO date string YYYY-MM-DD
 * @returns {string}     e.g. "resume/bullets/2025-03-26.json"
 */
export function bulletsPathnameForDate(date) {
  return `${DAILY_BULLETS_PREFIX}${date}.json`;
}

/**
 * Save (overwrite) a daily bullet-cache document in Vercel Blob.
 *
 * The document shape is defined by DAILY_BULLETS_SCHEMA_VERSION and is
 * always written to the stable pathname `resume/bullets/{date}.json`.
 *
 * DailyBulletsDocument shape:
 *   {
 *     schemaVersion: 1,
 *     date: "YYYY-MM-DD",
 *     generatedAt: ISO string,
 *     sourceType: "work_log_batch",
 *     bullets: DailyBulletItem[]
 *   }
 *
 * DailyBulletItem shape:
 *   {
 *     id: string,                        // "bullet-{date}-{index}"
 *     text: string,                      // raw bullet text from work log
 *     category: "company"|"opensource"|"other",
 *     suggestedSection: "experience"|"skills"|"projects",
 *     status: "pending"|"promoted"|"dismissed",
 *     promotedSuggestionId: string|null, // set when status becomes "promoted"
 *     createdAt: ISO string
 *   }
 *
 * @param {string} date  ISO date string YYYY-MM-DD
 * @param {object} data  DailyBulletsDocument
 * @returns {Promise<{ url: string }>}
 */
export async function saveDailyBullets(date, data) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const pathname = bulletsPathnameForDate(date);
  const json = JSON.stringify(data, null, 2);

  const result = await put(pathname, json, {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Download and parse the daily bullet-cache document for a specific date.
 *
 * Returns `null` when no cache exists for that date.
 *
 * @param {string} date  ISO date string YYYY-MM-DD
 * @returns {Promise<object|null>}  DailyBulletsDocument or null
 */
export async function readDailyBullets(date) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const pathname = bulletsPathnameForDate(date);

  const { blobs } = await list({
    prefix: pathname,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === pathname);
  if (!match) return null;

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch daily bullets for ${date}: ${response.status}`);
  }
  return response.json();
}

/**
 * List all dates for which a bullet-cache document exists in Vercel Blob.
 *
 * Returns dates sorted descending (most recent first), e.g. ["2025-03-26", "2025-03-25"].
 *
 * @returns {Promise<string[]>}
 */
export async function listBulletDates() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: DAILY_BULLETS_PREFIX,
    ...(token ? { token } : {})
  });

  return blobs
    .map((b) => {
      // pathname looks like "resume/bullets/2025-03-26.json"
      const filename = b.pathname.slice(DAILY_BULLETS_PREFIX.length);
      return filename.replace(/\.json$/, "");
    })
    .filter((d) => /^\d{4}-\d{2}-\d{2}$/.test(d))
    .sort()
    .reverse();
}

/**
 * Delete the daily bullet-cache document for a specific date from Vercel Blob.
 *
 * No-op when the cache does not exist for the given date.
 * Errors are propagated to the caller (unlike the write helpers, deletion is
 * an explicit user-triggered action so the caller should handle failures).
 *
 * @param {string} date  ISO date string YYYY-MM-DD
 * @returns {Promise<void>}
 */
export async function deleteDailyBullets(date) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const pathname = bulletsPathnameForDate(date);

  const { blobs } = await list({
    prefix: pathname,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === pathname);
  if (!match) return; // Nothing to delete.

  await del(match.url, ...(token ? [{ token }] : []));
}

/**
 * Soft-invalidate the daily bullet-cache document for a specific date.
 *
 * Marks the existing document with `invalidatedAt` and `invalidationReason` so
 * that the data is retained for auditing while callers that check `invalidatedAt`
 * treat the document as stale.  This is a non-destructive alternative to
 * `deleteDailyBullets`.
 *
 * If no document exists for the given date this is a no-op.
 * If the fetch or write fails, the error is logged and swallowed so invalidation
 * never breaks the caller.
 *
 * @param {string} date               ISO date string YYYY-MM-DD
 * @param {string} [reason="explicit"] Human-readable reason for invalidation
 * @returns {Promise<void>}
 */
export async function invalidateDailyBullets(date, reason = "explicit") {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const pathname = bulletsPathnameForDate(date);

  // Locate the existing document.
  let match;
  try {
    const { blobs } = await list({
      prefix: pathname,
      limit: 1,
      ...(token ? { token } : {})
    });
    match = blobs.find((b) => b.pathname === pathname);
  } catch (err) {
    console.warn(
      `[blob] invalidateDailyBullets list failed for date=${date}:`,
      err.message ?? String(err)
    );
    return;
  }

  if (!match) return; // No document to invalidate — no-op.

  // Fetch current content.
  let data;
  try {
    const response = await fetch(match.url);
    if (!response.ok) return;
    data = await response.json();
  } catch (err) {
    console.warn(
      `[blob] invalidateDailyBullets fetch failed for date=${date}:`,
      err.message ?? String(err)
    );
    return;
  }

  // Apply invalidation metadata and write back.
  const invalidated = {
    ...data,
    invalidatedAt: new Date().toISOString(),
    invalidationReason: String(reason)
  };

  try {
    await put(pathname, JSON.stringify(invalidated, null, 2), {
      access: "public",
      contentType: "application/json; charset=utf-8",
      addRandomSuffix: false,
      allowOverwrite: true,
      ...(token ? { token } : {})
    });
    console.info(`[blob] invalidateDailyBullets INVALIDATED for date=${date}, reason=${reason}`);
  } catch (err) {
    console.warn(
      `[blob] invalidateDailyBullets write failed for date=${date}:`,
      err.message ?? String(err)
    );
  }
}

// ─── PDF text storage (for reconstruction fallback) ────────────────────────────

/**
 * Save the plain text extracted from the uploaded PDF resume.
 *
 * Stored at `resume/pdf-text.txt` and retrieved later by the reconstruction
 * fallback so the user does not need to re-upload the PDF when bullets are
 * rebuilt from work logs.
 *
 * @param {string} text  Plain text extracted from the PDF (from pdf-parse)
 * @returns {Promise<{ url: string }>}
 */
export async function savePdfText(text) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const result = await put(PDF_TEXT_PATHNAME, text, {
    access: "public",
    contentType: "text/plain; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Read the stored PDF plain text from Vercel Blob.
 *
 * Returns `null` when no PDF text has been saved yet.
 *
 * @returns {Promise<string|null>}
 */
export async function readPdfText() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: PDF_TEXT_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === PDF_TEXT_PATHNAME);
  if (!match) return null;

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch PDF text: ${response.status}`);
  }
  return response.text();
}

// ─── Raw PDF binary storage ────────────────────────────────────────────────────

/**
 * Save the raw PDF binary uploaded at bootstrap time.
 *
 * Stored at `resume/resume.pdf` so the original file is preserved in
 * Vercel Blob (file-based → Blob 1:1 mapping principle).
 *
 * @param {Buffer} buffer  Raw PDF binary buffer
 * @returns {Promise<{ url: string }>}
 */
export async function savePdfRaw(buffer) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const result = await put(PDF_RAW_PATHNAME, buffer, {
    access: "public",
    contentType: "application/pdf",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Check whether the raw PDF binary exists in Vercel Blob.
 *
 * Returns null when no PDF has been saved yet.
 *
 * @returns {Promise<{ url: string, uploadedAt: string, size: number } | null>}
 */
export async function checkPdfRawExists() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: PDF_RAW_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === PDF_RAW_PATHNAME);
  if (!match) return null;

  return {
    url: match.url,
    uploadedAt: match.uploadedAt,
    size: match.size
  };
}

// ─── Keyword cluster axes storage ─────────────────────────────────────────────

/**
 * Save (overwrite) the keyword cluster axes document in Vercel Blob.
 *
 * Document shape:
 *   {
 *     schemaVersion: 1,
 *     generatedAt: ISO string,
 *     axes: Axis[]             // each Axis has { id, label, keywords[], _source }
 *   }
 *
 * @param {object} axesDoc  Keyword cluster axes document
 * @returns {Promise<{ url: string }>}
 */
export async function saveKeywordClusterAxes(axesDoc) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const json = JSON.stringify(axesDoc, null, 2);

  const result = await put(KEYWORD_CLUSTER_AXES_PATHNAME, json, {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Download and parse the keyword cluster axes document from Vercel Blob.
 *
 * Returns `null` when no keyword cluster axes have been saved yet.
 *
 * @returns {Promise<object|null>}  Keyword cluster axes document or null
 */
export async function readKeywordClusterAxes() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: KEYWORD_CLUSTER_AXES_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === KEYWORD_CLUSTER_AXES_PATHNAME);
  if (!match) return null;

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch keyword cluster axes: ${response.status}`);
  }
  return response.json();
}

// ─── Display axes storage ─────────────────────────────────────────────────────

/**
 * Save (overwrite) the display axes document in Vercel Blob as an independent
 * entity, separate from the main resume document.
 *
 * This is the authoritative write path for axes generated by the LLM axis-
 * clustering pipeline.  Storing axes here lets GET /api/resume/axes serve
 * requests without downloading the full resume/data.json.
 *
 * Document shape (DisplayAxesDocument):
 *   {
 *     schemaVersion: 1,
 *     generatedAt: ISO string,
 *     axes: Axis[]    // each Axis has { id, label, keywords[], _source }
 *   }
 *
 * @param {object} axesDoc  Display axes document
 * @returns {Promise<{ url: string }>}
 */
export async function saveDisplayAxes(axesDoc) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const json = JSON.stringify(axesDoc, null, 2);

  const result = await put(DISPLAY_AXES_PATHNAME, json, {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Download and parse the display axes document from Vercel Blob.
 *
 * Returns `null` when no display axes have been saved yet (e.g. before the
 * first POST /api/resume/axes call).  Callers should fall back to reading
 * `resume.display_axes` from the main resume document in that case.
 *
 * @returns {Promise<object|null>}  DisplayAxesDocument or null
 */
export async function readDisplayAxes() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: DISPLAY_AXES_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === DISPLAY_AXES_PATHNAME);
  if (!match) return null;

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch display axes: ${response.status}`);
  }
  return response.json();
}

// ─── Reconstruction marker ──────────────────────────────────────────────────────

/**
 * Write the reconstruction-needed marker to Vercel Blob.
 *
 * When this marker exists, the next GET /api/resume call with `?rebuild=1`
 * or a POST /api/resume/rebuild request will trigger a full reconstruction.
 *
 * @param {string} [reason="explicit"]  Human-readable reason for the rebuild request
 * @returns {Promise<void>}
 */
export async function markResumeForReconstruction(reason = "explicit") {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const marker = JSON.stringify({
    markedAt: new Date().toISOString(),
    reason: String(reason)
  });

  await put(RECONSTRUCTION_MARKER_PATHNAME, marker, {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });
}

/**
 * Remove the reconstruction-needed marker from Vercel Blob.
 *
 * Called after a successful reconstruction so the marker is not
 * indefinitely re-triggered.
 *
 * @returns {Promise<void>}
 */
export async function clearReconstructionMarker() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  // Locate the marker to get its URL (del() needs the full URL).
  const { blobs } = await list({
    prefix: RECONSTRUCTION_MARKER_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === RECONSTRUCTION_MARKER_PATHNAME);
  if (!match) return; // Nothing to clear.

  try {
    await del(match.url, ...(token ? [{ token }] : []));
  } catch (err) {
    // Best-effort deletion; caller should not fail on this.
    console.warn("[blob] clearReconstructionMarker del failed:", err.message ?? String(err));
  }
}

/**
 * Check whether a reconstruction-needed marker exists in Vercel Blob.
 *
 * @returns {Promise<{ needsRebuild: false } | { needsRebuild: true, markedAt: string, reason: string }>}
 */
export async function checkReconstructionMarker() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: RECONSTRUCTION_MARKER_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === RECONSTRUCTION_MARKER_PATHNAME);
  if (!match) return { needsRebuild: false };

  // Fetch marker content for reason / timestamp.
  try {
    const response = await fetch(match.url);
    if (response.ok) {
      const data = await response.json();
      return {
        needsRebuild: true,
        markedAt: data.markedAt ?? match.uploadedAt,
        reason: data.reason ?? "explicit"
      };
    }
  } catch {
    // If we can't read the content, the marker still exists → signal rebuild.
  }

  return {
    needsRebuild: true,
    markedAt: match.uploadedAt,
    reason: "explicit"
  };
}

// ─── Resume snapshots ───────────────────────────────────────────────────────

/**
 * Derive a stable, filesystem-safe Blob pathname for a snapshot from a
 * given ISO timestamp (colons replaced with hyphens).
 *
 * @param {string} isoTimestamp  e.g. "2025-03-27T12:00:00.000Z"
 * @returns {string}             e.g. "resume/snapshots/2025-03-27T12-00-00.000Z.json"
 */
export function snapshotPathnameFor(isoTimestamp) {
  const safe = isoTimestamp.replace(/:/g, "-");
  return `${SNAPSHOTS_PREFIX}${safe}.json`;
}

/**
 * Save the current resume state as an immutable snapshot in Vercel Blob.
 *
 * Each snapshot is stored at a unique, timestamped pathname so it is never
 * overwritten.  The document structure wraps the resume in a metadata envelope:
 *
 *   {
 *     schemaVersion: 1,
 *     snapshotKey:   "resume/snapshots/{safe-timestamp}.json",
 *     snapshotAt:    ISO string,
 *     label:         string,             // human-readable reason (e.g. "approve")
 *     trigger:       string,             // machine action trigger (e.g. "approve")
 *     triggeredBy:   string,             // e.g. "approve", "patch", "rollback"
 *     resume:        { ...resumeDoc }
 *   }
 *
 * @param {object} resumeDoc           The living-resume document to snapshot
 * @param {{ label?: string, trigger?: string, triggeredBy?: string }} [meta]  Optional metadata
 * @returns {Promise<{ snapshotKey: string, url: string }>}
 */
export async function saveSnapshot(resumeDoc, meta = {}) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const now = new Date().toISOString();
  const pathname = snapshotPathnameFor(now);

  const envelope = {
    schemaVersion: 1,
    snapshotKey: pathname,
    snapshotAt: now,
    label: meta.label ?? "manual",
    trigger: meta.trigger ?? "unknown",
    triggeredBy: meta.triggeredBy ?? "unknown",
    resume: resumeDoc
  };

  const result = await put(pathname, JSON.stringify(envelope, null, 2), {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: false,
    ...(token ? { token } : {})
  });

  return { snapshotKey: pathname, url: result.url };
}

/**
 * List all resume snapshots stored in Vercel Blob, sorted most-recent first.
 *
 * Each entry in the returned array includes:
 *   {
 *     snapshotKey: string,   // the pathname (usable in rollback requests)
 *     url: string,
 *     uploadedAt: string,    // ISO string from Blob metadata
 *     size: number
 *   }
 *
 * @returns {Promise<Array<{ snapshotKey: string, url: string, uploadedAt: string, size: number }>>}
 */
export async function listSnapshots() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: SNAPSHOTS_PREFIX,
    ...(token ? { token } : {})
  });

  return blobs
    .filter((b) => b.pathname.startsWith(SNAPSHOTS_PREFIX) && b.pathname.endsWith(".json"))
    .map((b) => ({
      snapshotKey: b.pathname,
      url: b.url,
      uploadedAt: b.uploadedAt,
      size: b.size
    }))
    .sort((a, b) => (a.uploadedAt < b.uploadedAt ? 1 : -1)); // most-recent first
}

/**
 * Read and parse a snapshot by its Blob pathname key.
 *
 * Returns the full snapshot envelope (including the nested `resume` field)
 * or `null` when the snapshot does not exist.
 *
 * @param {string} snapshotKey  e.g. "resume/snapshots/2025-03-27T12-00-00.000Z.json"
 * @returns {Promise<object|null>}  Snapshot envelope or null
 */
export async function readSnapshotByKey(snapshotKey) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: snapshotKey,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === snapshotKey);
  if (!match) return null;

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch snapshot (${snapshotKey}): ${response.status}`);
  }
  return response.json();
}

// ─── LinkedIn import storage ─────────────────────────────────────────────────

/**
 * Save (overwrite) the LinkedIn import document in Vercel Blob.
 *
 * This is a one-shot write during onboarding: the caller passes the parsed
 * ProfileData together with its source tag.  The document is wrapped in a
 * metadata envelope for provenance tracking.
 *
 * Stored at `resume/linkedin-import.json` with `allowOverwrite: true` so
 * the user can re-import if the first upload was wrong.
 *
 * @param {object} profileData  Parsed ProfileData from parseLinkedInFile
 * @param {string} source       "linkedin_pdf" | "linkedin_zip"
 * @returns {Promise<{ url: string }>}
 */
export async function saveLinkedInImport(profileData, source) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const envelope = {
    schemaVersion: 1,
    importedAt: new Date().toISOString(),
    source: String(source),
    data: profileData
  };

  const result = await put(LINKEDIN_IMPORT_PATHNAME, JSON.stringify(envelope, null, 2), {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Download and parse the stored LinkedIn import document from Vercel Blob.
 *
 * Returns `null` when no LinkedIn import has been saved yet.
 *
 * @returns {Promise<{ schemaVersion: number, importedAt: string, source: string, data: object }|null>}
 */
export async function readLinkedInImport() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: LINKEDIN_IMPORT_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === LINKEDIN_IMPORT_PATHNAME);
  if (!match) return null;

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch LinkedIn import data: ${response.status}`);
  }
  return response.json();
}

/**
 * Delete the LinkedIn import document from Vercel Blob.
 *
 * No-op when no import document exists.
 * Exposed for administrative cleanup; not called in the normal flow.
 *
 * @returns {Promise<void>}
 */
export async function clearLinkedInImport() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: LINKEDIN_IMPORT_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === LINKEDIN_IMPORT_PATHNAME);
  if (!match) return;

  try {
    await del(match.url, ...(token ? [{ token }] : []));
  } catch (err) {
    console.warn("[blob] clearLinkedInImport del failed:", err.message ?? String(err));
  }
}

// ─── Strength keywords storage ─────────────────────────────────────────────────

/**
 * Save (overwrite) the strength-keywords document in Vercel Blob.
 *
 * Stores a StrengthKeywordsDocument at the stable pathname
 * `resume/strength-keywords.json` using `allowOverwrite: true` so that
 * repeated writes always update the same canonical file.
 *
 * The document shape is defined in resumeTypes.mjs (StrengthKeywordsDocument):
 *   {
 *     schemaVersion: 1,
 *     updatedAt: ISO string,
 *     source: "bootstrap" | "user" | "system",
 *     keywords: string[]
 *   }
 *
 * @param {import("./resumeTypes.mjs").StrengthKeywordsDocument} doc
 * @returns {Promise<{ url: string }>}
 */
export async function saveStrengthKeywords(doc) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const json = JSON.stringify(doc, null, 2);

  const result = await put(STRENGTH_KEYWORDS_PATHNAME, json, {
    access: "public",
    contentType: "application/json; charset=utf-8",
    addRandomSuffix: false,
    allowOverwrite: true,
    ...(token ? { token } : {})
  });

  return { url: result.url };
}

/**
 * Download and parse the strength-keywords document from Vercel Blob.
 *
 * Returns a default empty StrengthKeywordsDocument when no file has been
 * saved yet (i.e. before the first bootstrap).  This makes `readStrengthKeywords`
 * safe to call unconditionally — callers never need to handle a null result.
 *
 * Initialization contract:
 *   When the file does not exist, the returned document has:
 *     { schemaVersion: 1, updatedAt: <now>, source: "system", keywords: [] }
 *
 * @returns {Promise<import("./resumeTypes.mjs").StrengthKeywordsDocument>}
 */
export async function readStrengthKeywords() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  const { blobs } = await list({
    prefix: STRENGTH_KEYWORDS_PATHNAME,
    limit: 1,
    ...(token ? { token } : {})
  });

  const match = blobs.find((b) => b.pathname === STRENGTH_KEYWORDS_PATHNAME);
  if (!match) {
    // Return initialized empty document — no storage yet (pre-bootstrap state).
    return {
      schemaVersion: 1,
      updatedAt: new Date().toISOString(),
      source: "system",
      keywords: []
    };
  }

  const response = await fetch(match.url);
  if (!response.ok) {
    throw new Error(`Failed to fetch strength keywords: ${response.status}`);
  }
  return response.json();
}
