/**
 * Resume Reconstruction — Full rebuild from original sources.
 *
 * When the cached resume document is missing, stale, or explicitly invalidated,
 * this module rebuilds all resume bullets from:
 *   1. The original PDF plain text stored in Vercel Blob at bootstrap time
 *   2. Accumulated daily work-log bullet candidates (data/daily/*.json on disk)
 *
 * The LLM is called with the combined source material to regenerate a fully
 * structured resume.  User-edited fields (sections where _source / _sources
 * is "user") are preserved and layered on top of the reconstructed result so
 * that user edits always win over system merges.
 *
 * Key functions:
 *   gatherWorkLogBullets(dataDir)        — scan daily JSON files on disk
 *   reconstructResumeFromSources(input)  — LLM call → BootstrapResult
 *   mergeWithUserEdits(current, fresh)   — preserve user edits
 *   isResumeStale(resume, workLogDates)  — staleness predicate
 *
 * Environment variables:
 *   OPENAI_API_KEY            — required for LLM call
 *   WORK_LOG_OPENAI_URL       — optional endpoint override
 *   WORK_LOG_OPENAI_MODEL     — optional model override (default: gpt-5.4-mini)
 *   WORK_LOG_DISABLE_OPENAI   — set "1" to disable (throws)
 *   RESUME_STALE_DAYS         — days before resume is considered stale (default: 7)
 */

import fs from "node:fs/promises";
import path from "node:path";

import { fileExists } from "./utils.mjs";
import { extractResumeUpdatesFromWorkLog } from "./resumeWorkLogExtract.mjs";
import { writeExtractCache } from "./bulletCache.mjs";

const OPENAI_URL =
  process.env.WORK_LOG_OPENAI_URL || "https://api.openai.com/v1/responses";
const OPENAI_MODEL = process.env.WORK_LOG_OPENAI_MODEL || "gpt-5.4-mini";

/** How many days old a resume must be (without a newer work log) to be stale. */
const STALE_THRESHOLD_DAYS = Math.max(
  1,
  parseInt(process.env.RESUME_STALE_DAYS || "7", 10) || 7
);

// ---------------------------------------------------------------------------
// Public: work-log scanning
// ---------------------------------------------------------------------------

/**
 * Scan the `data/daily/` directory and collect resume bullet candidates from
 * every available daily work-log JSON file.
 *
 * Each returned entry corresponds to one work-log day and contains the raw
 * bullet strings that were generated by the batch pipeline.  The caller can
 * filter or limit these entries before passing them to the LLM.
 *
 * @param {string} dataDir  Absolute path to the `data/` directory
 *                          (from config.dataDir).
 * @returns {Promise<WorkLogEntry[]>}
 *
 * @typedef {Object} WorkLogEntry
 * @property {string}   date                YYYY-MM-DD
 * @property {string[]} candidates          Combined candidate bullets
 * @property {string[]} companyCandidates   Company-project bullets
 * @property {string[]} openSourceCandidates Open-source project bullets
 */
export async function gatherWorkLogBullets(dataDir) {
  const dailyDir = path.join(dataDir, "daily");
  if (!(await fileExists(dailyDir))) return [];

  let entries;
  try {
    entries = await fs.readdir(dailyDir);
  } catch {
    return [];
  }

  const jsonFiles = entries
    .filter((name) => /^\d{4}-\d{2}-\d{2}\.json$/.test(name))
    .sort(); // ascending order

  const result = [];

  for (const filename of jsonFiles) {
    const date = filename.replace(/\.json$/, "");
    const filePath = path.join(dailyDir, filename);
    try {
      const raw = await fs.readFile(filePath, "utf8");
      const parsed = JSON.parse(raw);
      const resumeSection = parsed.resume;
      if (!resumeSection) continue;

      result.push({
        date,
        candidates: Array.isArray(resumeSection.candidates)
          ? resumeSection.candidates.filter((s) => typeof s === "string" && s.trim())
          : [],
        companyCandidates: Array.isArray(resumeSection.companyCandidates)
          ? resumeSection.companyCandidates.filter((s) => typeof s === "string" && s.trim())
          : [],
        openSourceCandidates: Array.isArray(resumeSection.openSourceCandidates)
          ? resumeSection.openSourceCandidates.filter((s) => typeof s === "string" && s.trim())
          : []
      });
    } catch {
      // Skip unparseable files; reconstruction continues with remaining data.
    }
  }

  return result;
}

// ---------------------------------------------------------------------------
// Public: staleness check
// ---------------------------------------------------------------------------

/**
 * Determine whether the stored resume is stale relative to available work logs.
 *
 * A resume is considered stale when:
 *   1. Its rebuild/generation timestamp is older than STALE_THRESHOLD_DAYS and
 *      there is at least one work-log entry newer than that timestamp, OR
 *   2. The resume has never been rebuilt (`meta.rebuiltAt` is absent) and
 *      work-log entries exist that post-date `meta.generatedAt`.
 *
 * @param {object}        resume        The stored resume document.
 * @param {WorkLogEntry[]} workLogEntries  Entries from gatherWorkLogBullets().
 * @returns {{ isStale: boolean, latestLogDate: string|null, checkpointDate: string|null }}
 */
export function isResumeStale(resume, workLogEntries) {
  if (!Array.isArray(workLogEntries) || workLogEntries.length === 0) {
    return { isStale: false, latestLogDate: null, checkpointDate: null };
  }

  // Latest date among gathered work logs
  const sortedDates = workLogEntries.map((e) => e.date).sort();
  const latestLogDate = sortedDates[sortedDates.length - 1];

  // The reference timestamp to compare against (rebuiltAt preferred over generatedAt)
  const checkpointIso =
    resume?.meta?.rebuiltAt ?? resume?.meta?.generatedAt ?? null;

  if (!checkpointIso) {
    // No timestamp at all — treat as stale when any work logs exist
    return { isStale: true, latestLogDate, checkpointDate: null };
  }

  const checkpointDate = checkpointIso.slice(0, 10); // YYYY-MM-DD

  // Is the latest log file newer than the last checkpoint?
  if (latestLogDate > checkpointDate) {
    // Additional guard: only flag as stale if the checkpoint itself is older
    // than the threshold (prevents false-positives on same-day batches).
    const checkpointMs = new Date(checkpointIso).getTime();
    const nowMs = Date.now();
    const ageMs = nowMs - checkpointMs;
    const thresholdMs = STALE_THRESHOLD_DAYS * 24 * 60 * 60 * 1000;

    if (ageMs >= thresholdMs) {
      return { isStale: true, latestLogDate, checkpointDate };
    }
  }

  return { isStale: false, latestLogDate, checkpointDate };
}

// ---------------------------------------------------------------------------
// Public: LLM-based reconstruction
// ---------------------------------------------------------------------------

/**
 * Reconstruct a complete resume document from the original PDF text and
 * accumulated work-log bullet candidates via a single LLM call.
 *
 * When OpenAI is unavailable (missing key or disabled), the function returns
 * the current resume unchanged rather than throwing, so the caller can
 * degrade gracefully.
 *
 * @param {Object} input
 * @param {string}         input.pdfText          Plain text from the original PDF
 *                                                 (stored in resume/pdf-text.txt).
 * @param {WorkLogEntry[]} input.workLogEntries    Entries from gatherWorkLogBullets().
 * @param {object}         input.currentResume     The current live resume document
 *                                                 (for context and user-edit preservation).
 * @returns {Promise<ReconstructionResult>}
 *
 * @typedef {Object} ReconstructionResult
 * @property {object}   resumeData       Freshly reconstructed resume document
 * @property {string[]} strengthKeywords Updated strength keywords
 * @property {object[]} displayAxes      Updated display axes
 */
export async function reconstructResumeFromSources(input) {
  const { pdfText, workLogEntries, currentResume } = input;

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "OPENAI_API_KEY is not set — cannot reconstruct resume from sources"
    );
  }
  if (process.env.WORK_LOG_DISABLE_OPENAI === "1") {
    throw new Error(
      "OpenAI integration is disabled (WORK_LOG_DISABLE_OPENAI=1)"
    );
  }

  const payload = buildReconstructionPayload({ pdfText, workLogEntries, currentResume });

  const response = await fetch(OPENAI_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Reconstruction LLM call failed: ${response.status} ${errorText.slice(0, 400)}`
    );
  }

  const data = await response.json();
  const rawText = data.output_text || extractOutputText(data);
  if (!rawText) {
    throw new Error("Reconstruction LLM call returned empty output");
  }

  const parsed = JSON.parse(rawText);
  return normalizeReconstructionResult(parsed, currentResume);
}

// ---------------------------------------------------------------------------
// Public: merge user edits over fresh reconstruction
// ---------------------------------------------------------------------------

/**
 * Merge a freshly reconstructed resume with the current live document,
 * ensuring that every user-edited field is preserved unchanged.
 *
 * Merge rules:
 *   • `summary`         — preserved when `_sources.summary === "user"` or `"user_approved"`
 *   • `contact`         — preserved when `_sources.contact === "user"` or `"user_approved"`
 *   • `skills`          — preserved when `_sources.skills === "user"` or `"user_approved"`
 *   • `experience[i]`   — preserved entirely when `_source === "user"` or `"user_approved"`;
 *                         system entries are replaced with the fresh reconstruction
 *   • `education`       — always kept from the current resume (structural, not
 *                         derived from work logs)
 *   • `projects`        — user-edited/approved entries preserved; new system entries added
 *   • `certifications`  — always kept from the current resume
 *   • `meta`            — current bootstrapped metadata preserved; `rebuiltAt`
 *                         is stamped to the current time
 *
 * @param {object} current      The existing live resume document (may have user edits)
 * @param {ReconstructionResult} reconstructionResult  Result from reconstructResumeFromSources()
 * @returns {object}  The merged resume document
 */
export function mergeWithUserEdits(current, { resumeData, strengthKeywords, displayAxes }) {
  const fresh = resumeData ?? {};
  const cur = current ?? {};

  // ── meta: preserve original bootstrap metadata, stamp rebuiltAt ───────────
  const mergedMeta = {
    ...(fresh.meta ?? {}),
    // Critical provenance fields from the original bootstrap
    language:      cur.meta?.language    ?? fresh.meta?.language    ?? "en",
    source:        cur.meta?.source      ?? fresh.meta?.source      ?? "pdf",
    generatedAt:   cur.meta?.generatedAt ?? fresh.meta?.generatedAt ?? new Date().toISOString(),
    schemaVersion: cur.meta?.schemaVersion ?? 1,
    pdf_name:      cur.meta?.pdf_name    ?? fresh.meta?.pdf_name    ?? null,
    linkedin_url:  cur.meta?.linkedin_url ?? fresh.meta?.linkedin_url ?? null,
    // Reconstruction timestamp
    rebuiltAt: new Date().toISOString()
  };

  // ── _sources: start with fresh, then overlay user overrides ───────────────
  const curSrc = cur._sources ?? {};
  const freshSrc = fresh._sources ?? {};
  const mergedSources = { ...freshSrc };

  // Helper: returns true when a source value represents human-confirmed content
  // (either directly authored or explicitly approved via the suggestions UI).
  const isHumanConfirmed = (src) => src === "user" || src === "user_approved";

  // ── Scalar sections: preserve user-edited/approved versions ───────────────
  const mergedSummary =
    isHumanConfirmed(curSrc.summary) ? cur.summary : (fresh.summary ?? cur.summary ?? "");
  if (isHumanConfirmed(curSrc.summary)) mergedSources.summary = curSrc.summary;

  const mergedContact =
    isHumanConfirmed(curSrc.contact) ? { ...cur.contact } : (fresh.contact ?? cur.contact);
  if (isHumanConfirmed(curSrc.contact)) mergedSources.contact = curSrc.contact;

  const mergedSkills =
    isHumanConfirmed(curSrc.skills)
      ? { ...cur.skills }
      : (fresh.skills ?? cur.skills ?? { technical: [], languages: [], tools: [] });
  if (isHumanConfirmed(curSrc.skills)) mergedSources.skills = curSrc.skills;

  // ── Experience: user-edited/approved entries win; system entries refreshed ─
  const curExp = Array.isArray(cur.experience) ? cur.experience : [];
  const freshExp = Array.isArray(fresh.experience) ? fresh.experience : [];

  const userExp = curExp.filter((e) => isHumanConfirmed(e._source));
  const userCompanies = new Set(
    userExp.map((e) => (e.company ?? "").toLowerCase().trim()).filter(Boolean)
  );
  // Keep system entries from the fresh reconstruction that don't clash with
  // user-edited/approved entries.
  const systemExp = freshExp.filter(
    (e) => !userCompanies.has((e.company ?? "").toLowerCase().trim())
  );
  const mergedExperience = [...userExp, ...systemExp];

  // ── Education: static — always keep current (not derived from work logs) ──
  const mergedEducation =
    Array.isArray(cur.education) && cur.education.length > 0
      ? cur.education
      : (fresh.education ?? []);

  // ── Projects: user-edited/approved entries win; new system entries appended ─
  const curProj = Array.isArray(cur.projects) ? cur.projects : [];
  const freshProj = Array.isArray(fresh.projects) ? fresh.projects : [];
  const userProj = curProj.filter((p) => isHumanConfirmed(p._source));
  const userProjNames = new Set(
    userProj.map((p) => (p.name ?? "").toLowerCase().trim()).filter(Boolean)
  );
  const systemProj = freshProj.filter(
    (p) => !userProjNames.has((p.name ?? "").toLowerCase().trim())
  );
  const mergedProjects =
    userProj.length > 0 ? [...userProj, ...systemProj] : (freshProj.length > 0 ? freshProj : curProj);

  // ── Certifications: static — always keep current ──────────────────────────
  const mergedCertifications =
    Array.isArray(cur.certifications) && cur.certifications.length > 0
      ? cur.certifications
      : (fresh.certifications ?? []);

  return {
    meta: mergedMeta,
    _sources: mergedSources,
    contact: mergedContact,
    summary: mergedSummary,
    experience: mergedExperience,
    education: mergedEducation,
    skills: mergedSkills,
    projects: mergedProjects,
    certifications: mergedCertifications,
    strength_keywords: Array.isArray(strengthKeywords) ? strengthKeywords : (cur.strength_keywords ?? []),
    display_axes: Array.isArray(displayAxes) ? displayAxes : (cur.display_axes ?? [])
  };
}

// ---------------------------------------------------------------------------
// Payload builder
// ---------------------------------------------------------------------------

function buildReconstructionPayload({ pdfText, workLogEntries, currentResume }) {
  return {
    model: OPENAI_MODEL,
    reasoning: { effort: "medium" },
    text: {
      format: {
        type: "json_schema",
        name: "resume_reconstruction",
        strict: true,
        schema: RECONSTRUCTION_OUTPUT_SCHEMA
      }
    },
    max_output_tokens: 4096,
    input: [
      {
        role: "system",
        content: [{ type: "input_text", text: RECONSTRUCTION_SYSTEM_PROMPT }]
      },
      {
        role: "user",
        content: [
          {
            type: "input_text",
            text: buildReconstructionUserMessage({ pdfText, workLogEntries, currentResume })
          }
        ]
      }
    ]
  };
}

function buildReconstructionUserMessage({ pdfText, workLogEntries, currentResume }) {
  const parts = [];

  // ── 1. Original PDF text (primary source) ─────────────────────────────────
  parts.push("=== ORIGINAL RESUME PDF TEXT ===");
  parts.push((pdfText || "").trim() || "(not available)");

  // ── 2. Current resume structure (for company/role context) ────────────────
  if (currentResume && typeof currentResume === "object") {
    const structureSummary = buildResumeSkeleton(currentResume);
    if (structureSummary) {
      parts.push("");
      parts.push("=== CURRENT RESUME STRUCTURE (for context — companies, titles, dates) ===");
      parts.push(structureSummary);
    }
  }

  // ── 3. Work-log bullet candidates ─────────────────────────────────────────
  if (Array.isArray(workLogEntries) && workLogEntries.length > 0) {
    // Limit to most recent 90 days of work-log data to keep prompt manageable
    const recent = workLogEntries.slice(-90);
    const allBullets = [];

    for (const entry of recent) {
      const bullets = [
        ...(entry.companyCandidates ?? []),
        ...(entry.openSourceCandidates ?? []),
        ...(entry.candidates ?? [])
      ];
      for (const b of bullets) {
        if (b && !allBullets.includes(b)) {
          allBullets.push(b);
        }
      }
    }

    if (allBullets.length > 0) {
      parts.push("");
      parts.push(
        `=== WORK LOG BULLET CANDIDATES (${workLogEntries.length} days, ${allBullets.length} bullets) ===`
      );
      // Cap at 200 bullets to stay within token budget
      allBullets.slice(0, 200).forEach((b) => parts.push(`- ${b}`));
    }
  }

  return parts.join("\n");
}

/**
 * Build a compact text summary of the current resume's structure (companies,
 * titles, dates) so the LLM can assign work-log bullets to the right roles.
 */
function buildResumeSkeleton(resume) {
  const lines = [];

  if (resume.contact?.name) {
    lines.push(`Name: ${resume.contact.name}`);
  }

  const exp = Array.isArray(resume.experience) ? resume.experience : [];
  if (exp.length > 0) {
    lines.push("Experience:");
    for (const e of exp) {
      const dates = [e.start_date, e.end_date].filter(Boolean).join(" – ");
      lines.push(
        `  - ${e.company || "(unknown)"}: ${e.title || "(unknown)"}${dates ? ` (${dates})` : ""}`
      );
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// System prompt
// ---------------------------------------------------------------------------

const RECONSTRUCTION_SYSTEM_PROMPT = `\
You are an expert resume writer tasked with REBUILDING and UPDATING a professional resume.

You have been given:
1. The original PDF resume text (source of truth for career history)
2. The current resume structure (companies, titles, dates — for reference)
3. Recent work-log bullet candidates (achievements recorded day-by-day from commits and AI sessions)

Your tasks:
━━━ REBUILD ━━━
Re-parse the PDF text to produce a fully structured resume.  Use the current
structure as guidance for company names and role titles.

━━━ INTEGRATE WORK LOGS ━━━
• Assign each work-log bullet to the most relevant experience entry (by company name).
• Merge them with bullets derived from the PDF.
• Remove redundant or near-duplicate bullets (keep the most specific/quantified version).
• Rewrite bullets in achievement-oriented active voice.  Start with a strong verb.
• Keep each bullet under 140 characters.
• Add at most 5 new bullets per role (quality over quantity).

━━━ LANGUAGE RULE ━━━
Detect the primary language of the PDF text (ISO 639-1, e.g. "ko", "en").
Write ALL generated text in that SAME language.

━━━ SECTIONS ━━━
• contact: name, email, phone, location, website, linkedin (null if not found)
• summary: 2-4 sentence professional summary in the source language
• experience: reverse-chronological; start_date/end_date in YYYY-MM; "present" for current; null if unknown
• education: reverse-chronological; gpa only if stated; null otherwise
• skills: technical (frameworks, libraries, paradigms), languages (programming/scripting), tools (platforms, CI/CD)
• projects: side projects or open-source contributions; empty array if none
• certifications: professional certs only; empty array if none

━━━ STRENGTH KEYWORDS ━━━
5–15 short marketable keywords (hard + soft skills, under 40 chars each).

━━━ DISPLAY AXES ━━━
2–4 distinct career narrative lenses (label + tagline + 3-6 highlight skills each).`;

// ---------------------------------------------------------------------------
// JSON Schema (mirrors resumeBootstrap.mjs schema structure)
// ---------------------------------------------------------------------------

const RECONSTRUCTION_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["resume", "strength_keywords", "display_axes"],
  properties: {
    resume: {
      type: "object",
      additionalProperties: false,
      required: [
        "language", "contact", "summary", "experience",
        "education", "skills", "projects", "certifications"
      ],
      properties: {
        language: { type: "string" },
        contact: {
          type: "object",
          additionalProperties: false,
          required: ["name", "email", "phone", "location", "website", "linkedin"],
          properties: {
            name:     { type: "string" },
            email:    { type: ["string", "null"] },
            phone:    { type: ["string", "null"] },
            location: { type: ["string", "null"] },
            website:  { type: ["string", "null"] },
            linkedin: { type: ["string", "null"] }
          }
        },
        summary: { type: "string" },
        experience: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["company", "title", "start_date", "end_date", "location", "bullets"],
            properties: {
              company:    { type: "string" },
              title:      { type: "string" },
              start_date: { type: ["string", "null"] },
              end_date:   { type: ["string", "null"] },
              location:   { type: ["string", "null"] },
              bullets:    { type: "array", items: { type: "string" } }
            }
          }
        },
        education: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["institution", "degree", "field", "start_date", "end_date", "gpa"],
            properties: {
              institution: { type: "string" },
              degree:      { type: ["string", "null"] },
              field:       { type: ["string", "null"] },
              start_date:  { type: ["string", "null"] },
              end_date:    { type: ["string", "null"] },
              gpa:         { type: ["string", "null"] }
            }
          }
        },
        skills: {
          type: "object",
          additionalProperties: false,
          required: ["technical", "languages", "tools"],
          properties: {
            technical: { type: "array", items: { type: "string" } },
            languages: { type: "array", items: { type: "string" } },
            tools:     { type: "array", items: { type: "string" } }
          }
        },
        projects: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["name", "description", "url", "bullets"],
            properties: {
              name:        { type: "string" },
              description: { type: ["string", "null"] },
              url:         { type: ["string", "null"] },
              bullets:     { type: "array", items: { type: "string" } }
            }
          }
        },
        certifications: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["name", "issuer", "date"],
            properties: {
              name:   { type: "string" },
              issuer: { type: ["string", "null"] },
              date:   { type: ["string", "null"] }
            }
          }
        }
      }
    },
    strength_keywords: {
      type: "array",
      items: { type: "string" }
    },
    display_axes: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["label", "tagline", "highlight_skills"],
        properties: {
          label:            { type: "string" },
          tagline:          { type: "string" },
          highlight_skills: { type: "array", items: { type: "string" } }
        }
      }
    }
  }
};

// ---------------------------------------------------------------------------
// Output normalisation
// ---------------------------------------------------------------------------

function normalizeReconstructionResult(parsed, currentResume) {
  const rawResume = parsed.resume ?? {};
  const language = normalizeLanguageCode(rawResume.language) ||
    (currentResume?.meta?.language ?? "en");

  const resumeData = {
    meta: {
      language,
      source: currentResume?.meta?.source ?? "pdf",
      generatedAt: currentResume?.meta?.generatedAt ?? new Date().toISOString(),
      schemaVersion: currentResume?.meta?.schemaVersion ?? 1
    },
    _sources: {
      summary: "system",
      contact: "system",
      skills:  "system"
    },
    contact:        normalizeContact(rawResume.contact),
    summary:        typeof rawResume.summary === "string" ? rawResume.summary.trim() : "",
    experience:     normalizeExperience(rawResume.experience),
    education:      normalizeEducation(rawResume.education),
    skills:         normalizeSkills(rawResume.skills),
    projects:       normalizeProjects(rawResume.projects),
    certifications: normalizeCertifications(rawResume.certifications)
  };

  const strengthKeywords = normalizeStringArray(parsed.strength_keywords, 40, 15);
  const displayAxes      = normalizeDisplayAxes(parsed.display_axes);

  return { resumeData, strengthKeywords, displayAxes };
}

function normalizeLanguageCode(raw) {
  if (typeof raw !== "string" || !raw.trim()) return "en";
  return raw.trim().toLowerCase().slice(0, 5);
}

function nullableString(value) {
  if (value === null || value === undefined) return null;
  const s = String(value).trim();
  return s || null;
}

function normalizeContact(raw) {
  if (!raw || typeof raw !== "object") {
    return { name: "", email: null, phone: null, location: null, website: null, linkedin: null };
  }
  return {
    name:     String(raw.name || "").trim(),
    email:    nullableString(raw.email),
    phone:    nullableString(raw.phone),
    location: nullableString(raw.location),
    website:  nullableString(raw.website),
    linkedin: nullableString(raw.linkedin)
  };
}

function normalizeExperience(arr) {
  if (!Array.isArray(arr)) return [];
  return arr
    .filter((item) => item && typeof item === "object" && item.company)
    .map((item) => ({
      _source:    "system",
      company:    String(item.company || "").trim(),
      title:      String(item.title   || "").trim(),
      start_date: nullableString(item.start_date),
      end_date:   nullableString(item.end_date),
      location:   nullableString(item.location),
      bullets:    normalizeStringArray(item.bullets, 160, 8)
    }));
}

function normalizeEducation(arr) {
  if (!Array.isArray(arr)) return [];
  return arr
    .filter((item) => item && typeof item === "object" && item.institution)
    .map((item) => ({
      _source:     "system",
      institution: String(item.institution || "").trim(),
      degree:      nullableString(item.degree),
      field:       nullableString(item.field),
      start_date:  nullableString(item.start_date),
      end_date:    nullableString(item.end_date),
      gpa:         nullableString(item.gpa)
    }));
}

function normalizeSkills(raw) {
  if (!raw || typeof raw !== "object") {
    return { technical: [], languages: [], tools: [] };
  }
  return {
    technical: normalizeStringArray(raw.technical, 60, 30),
    languages: normalizeStringArray(raw.languages, 40, 20),
    tools:     normalizeStringArray(raw.tools,      60, 30)
  };
}

function normalizeProjects(arr) {
  if (!Array.isArray(arr)) return [];
  return arr
    .filter((item) => item && typeof item === "object" && item.name)
    .map((item) => ({
      _source:     "system",
      name:        String(item.name || "").trim(),
      description: nullableString(item.description),
      url:         nullableString(item.url),
      bullets:     normalizeStringArray(item.bullets, 160, 6)
    }));
}

function normalizeCertifications(arr) {
  if (!Array.isArray(arr)) return [];
  return arr
    .filter((item) => item && typeof item === "object" && item.name)
    .map((item) => ({
      _source: "system",
      name:    String(item.name || "").trim(),
      issuer:  nullableString(item.issuer),
      date:    nullableString(item.date)
    }));
}

function normalizeDisplayAxes(arr) {
  if (!Array.isArray(arr)) return [];
  return arr
    .filter((item) => item && typeof item === "object" && item.label && item.tagline)
    .slice(0, 4)
    .map((item) => ({
      label:            String(item.label   || "").trim(),
      tagline:          String(item.tagline || "").trim(),
      highlight_skills: normalizeStringArray(item.highlight_skills, 60, 6)
    }));
}

function normalizeStringArray(value, maxItemLength = 200, maxItems = 20) {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => String(item || "").trim())
    .filter(Boolean)
    .map((item) => item.slice(0, maxItemLength))
    .slice(0, maxItems);
}

// ---------------------------------------------------------------------------
// Public: full extract-cache reconstruction (Sub-AC 14-3)
// ---------------------------------------------------------------------------

/**
 * Full reconstruction pipeline: derive WorkLogExtract for every raw work-log
 * entry, **bypassing the extract cache**, and write each result back to the
 * cache (re-hydration).
 *
 * This is the "hard reset" path.  Unlike the normal candidate-generation
 * pipeline — which calls `readExtractCache` first and short-circuits on a HIT —
 * this function always calls the LLM for every entry so the cache is
 * guaranteed to contain fresh results after the run.
 *
 * The function NEVER throws.  Per-entry LLM failures are counted in
 * `result.failed` and logged as warnings so the pipeline always completes.
 *
 * Dependency-injection parameters (`extractFn`, `writeCacheFn`) allow tests
 * to stub the LLM and cache layers without `--experimental-test-module-mocks`.
 *
 * @param {Object}         options
 * @param {WorkLogEntry[]} options.workLogEntries  Raw entries from gatherWorkLogBullets()
 * @param {object|null}    options.currentResume   Current live resume doc (used for
 *                                                 deduplication context in the LLM diff step).
 *                                                 May be null if no resume exists yet.
 * @param {Function}       [options.extractFn]     Injection: (workLogSummary, resume) → Promise<WorkLogExtract>
 *                                                 Defaults to extractResumeUpdatesFromWorkLog
 * @param {Function}       [options.writeCacheFn]  Injection: (date, extract) → Promise<void>
 *                                                 Defaults to writeExtractCache
 * @returns {Promise<ReconstructionStats>}
 *
 * @typedef {Object} ReconstructionStats
 * @property {number}   total     Total entries attempted
 * @property {number}   processed Entries where LLM extraction succeeded and cache was written
 * @property {number}   failed    Entries where LLM extraction threw an error
 * @property {number}   skipped   Entries without a valid date (defensive guard)
 * @property {string[]} dates     Dates successfully processed (ascending order)
 */
export async function fullReconstructExtractCache({
  workLogEntries,
  currentResume = null,
  extractFn = extractResumeUpdatesFromWorkLog,
  writeCacheFn = writeExtractCache
}) {
  const entries = Array.isArray(workLogEntries) ? workLogEntries : [];

  let processed = 0;
  let failed = 0;
  let skipped = 0;
  const dates = [];

  for (const entry of entries) {
    const { date } = entry;

    // Guard: skip entries with no valid date string
    if (!date || typeof date !== "string" || !date.trim()) {
      skipped++;
      continue;
    }

    // Adapt the raw WorkLogEntry into the shape expected by extractResumeUpdatesFromWorkLog.
    //
    // gatherWorkLogBullets returns:
    //   { date, candidates, companyCandidates, openSourceCandidates }
    //
    // extractResumeUpdatesFromWorkLog / buildWorkLogDiff reads:
    //   workLog.resume.candidates
    //   workLog.resume.companyCandidates
    //   workLog.resume.openSourceCandidates
    //
    // Wrapping under `resume` aligns the two interfaces without modifying either.
    const workLogSummary = {
      date,
      resume: {
        candidates:           Array.isArray(entry.candidates)           ? entry.candidates           : [],
        companyCandidates:    Array.isArray(entry.companyCandidates)    ? entry.companyCandidates    : [],
        openSourceCandidates: Array.isArray(entry.openSourceCandidates) ? entry.openSourceCandidates : []
      }
    };

    try {
      // ── Bypass cache: call extractFn directly (no readExtractCache) ──────────
      const extract = await extractFn(workLogSummary, currentResume);

      // ── Re-hydrate cache: write fresh result ─────────────────────────────────
      await writeCacheFn(date, extract);

      processed++;
      dates.push(date);
    } catch (err) {
      console.warn(
        `[resumeReconstruction/fullReconstructExtractCache] extract failed for date=${date}:`,
        err.message ?? String(err)
      );
      failed++;
    }
  }

  // Return dates in ascending chronological order (entries are already sorted
  // ascending from gatherWorkLogBullets, but re-sort defensively).
  dates.sort();

  return {
    total: entries.length,
    processed,
    failed,
    skipped,
    dates
  };
}

// ---------------------------------------------------------------------------
// Response extraction helper
// ---------------------------------------------------------------------------

function extractOutputText(data) {
  const outputs = data.output || [];
  const texts = [];
  for (const item of outputs) {
    const content = item?.content || [];
    for (const part of content) {
      if (part?.type === "output_text" && part?.text) {
        texts.push(part.text);
      }
    }
  }
  return texts.join("\n").trim();
}
