import { useState, useCallback, useEffect, useRef } from 'preact/hooks';
import { navigate } from '../App.jsx';
import { useDraftContext } from './useDraftContext.js';

/**
 * useResumeChat — 채팅 기반 이력서 구체화 세션의 핵심 상태 관리 훅
 *
 * 채팅 화면 진입 시 수행하는 작업:
 *   1. useDraftContext를 통해 캐시된 초안을 조회하고 없으면 자동 생성
 *   2. 현재 이력서 JSON을 로드하여 diff 기준점으로 보관 (initialResume)
 *   3. 고유 세션 ID를 생성하여 메시지 히스토리를 세션 단위로 관리
 *
 * 반환값:
 *   ── 초안(Draft) ──
 *   draft             — ResumeDraft | null      초안 데이터 (생성/캐시 로드 완료 시)
 *   draftStatus       — 'idle' | 'loading' | 'generating' | 'ready' | 'error'
 *   draftError        — string | null           초안 로딩/생성 오류
 *   draftRetry        — () => Promise<void>     초안 재생성 트리거
 *
 *   ── 메시지 ──
 *   messages          — ChatMessage[]           대화 메시지 목록
 *   setMessages       — (updater) => void       메시지 직접 업데이트 (diff 상태 변경 등)
 *
 *   ── 채팅 API ──
 *   sendMessage       — (parsedQuery) => Promise<void>  채팅 메시지 전송
 *   loading           — boolean                 API 응답 대기 중 여부
 *
 *   ── 세션 ──
 *   sessionId         — string                  현재 세션 고유 ID
 *
 *   ── 이력서 상태 (diff 비교용) ──
 *   initialResume     — object | null           세션 시작 시 이력서 스냅샷
 *   currentResume     — object | null           최신 이력서 (섹션 승인 후 갱신)
 *   refreshResume     — () => Promise<void>     최신 이력서 재조회
 *   approvedCount     — number                  세션 내 승인된 섹션 수
 *
 * @typedef {Object} ChatMessage
 * @property {string}  id
 * @property {'user'|'assistant'|'system'} role
 * @property {string}  content
 * @property {object}  [parsedQuery]    파싱된 질의 (사용자 메시지)
 * @property {number}  timestamp
 * @property {boolean} [error]          오류 메시지 여부
 * @property {object}  [diff]           섹션 diff 제안 { section, before, after, evidence? }
 * @property {'pending'|'queued'|'approved'|'rejected'} [diffStatus]
 * @property {object}  [jsonDiff]       전체 JSON diff { original, modified, evidence? }
 * @property {'pending'|'approved'|'rejected'} [jsonDiffStatus]
 * @property {Array}   [citations]      출처 증거 배열
 * @property {object}  [applyIntent]    "반영해줘" 의도 파싱 결과
 *
 * @param {Object} [opts]
 * @param {boolean} [opts.autoGenerateDraft=true]  캐시 없을 때 자동 생성
 * @param {string}  [opts.fromDate]                초안 생성 시작일 (YYYY-MM-DD)
 * @param {string}  [opts.toDate]                  초안 생성 종료일 (YYYY-MM-DD)
 */
export function useResumeChat({ autoGenerateDraft = true, fromDate, toDate } = {}) {
  /* ── 세션 ID — 탭 단위 고유 (MVP: 대화 지속성 없음) ─── */
  const [sessionId] = useState(
    () => `chat-${Date.now()}-${Math.random().toString(36).slice(2)}`
  );

  /* ── 초안(Draft) 로딩 — useDraftContext 위임 ─── */
  const {
    draft: insightDraft,
    status: draftStatus,
    error: draftError,
    generate: draftRetry,
  } = useDraftContext({
    autoGenerate: autoGenerateDraft,
    fromDate,
    toDate,
  });

  /**
   * insightDraft가 ready가 되면 상위 draft 상태에도 반영.
   * 채팅 API 요청 시 draftContext로 함께 전달된다.
   */
  const [draft, setDraft] = useState(null);
  useEffect(() => {
    if (draftStatus === 'ready' && insightDraft) {
      setDraft(insightDraft);
    }
  }, [draftStatus, insightDraft]);

  /* ── 메시지 히스토리 ─── */
  const [messages, setMessages] = useState([]);

  /* ── 채팅 API 로딩 상태 ─── */
  const [loading, setLoading] = useState(false);

  /* ── 이력서 상태 (diff 비교용, Sub-AC 5-3) ─── */
  const [initialResume, setInitialResume] = useState(null);
  const [currentResume, setCurrentResume] = useState(null);
  const [approvedCount, setApprovedCount] = useState(0);
  const initialResumeFetched = useRef(false);

  /** 세션 시작 시 현재 이력서를 로드하여 diff 기준점으로 보관 */
  useEffect(() => {
    if (initialResumeFetched.current) return;
    initialResumeFetched.current = true;

    fetch('/api/resume', { credentials: 'include' })
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => {
        if (data) setInitialResume(data);
      })
      .catch(() => {
        /* 비치명적 — diff 기능만 비활성화됨 */
      });
  }, []);

  /**
   * 최신 이력서를 서버에서 가져와 currentResume을 갱신한다.
   * 섹션 승인 완료 후 호출된다.
   */
  const refreshResume = useCallback(async () => {
    try {
      const res = await fetch('/api/resume', { credentials: 'include' });
      if (res.ok) {
        const data = await res.json();
        setCurrentResume(data);
        setApprovedCount((c) => c + 1);
      }
    } catch {
      /* 비치명적 */
    }
  }, []);

  /* ── 메시지 ID 생성 헬퍼 ─── */
  function makeId() {
    return `msg-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  }

  /**
   * 채팅 메시지 전송 — 사용자 입력을 메시지 목록에 추가하고 서버 API를 호출한다.
   *
   * 흐름:
   *   1. 사용자 메시지를 즉시 messages에 추가
   *   2. POST /api/resume/chat 로 서버 호출 (초안 컨텍스트 포함)
   *   3. 응답을 assistant 메시지로 추가 (diff, citations, applyIntent 포함)
   *   4. 오류 시 error 메시지 추가
   *
   * @param {ReturnType<import('../lib/resumeQueryParser.js').parseResumeQuery>} parsedQuery
   */
  const sendMessage = useCallback(
    async (parsedQuery) => {
      if (loading) return;

      // 사용자 메시지를 즉시 추가
      const userMessage = {
        id: makeId(),
        role: 'user',
        content: parsedQuery.raw,
        parsedQuery,
        timestamp: Date.now(),
      };
      const updatedMessages = [...messages, userMessage];
      setMessages(updatedMessages);
      setLoading(true);

      try {
        const res = await fetch('/api/resume/chat', {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            sessionId,
            query: parsedQuery.raw,
            parsedQuery: {
              intent: parsedQuery.intent,
              keywords: parsedQuery.keywords,
              section: parsedQuery.section,
              dateRange: parsedQuery.dateRange,
            },
            history: updatedMessages.map((m) => ({ role: m.role, content: m.content })),
            // 초안 컨텍스트를 함께 전달해 LLM이 업무 로그 근거를 활용할 수 있게 한다.
            draftContext: draft
              ? {
                  dateRange: draft.dateRange,
                  strengthCandidates: draft.strengthCandidates,
                  experienceSummaries: draft.experienceSummaries,
                  suggestedSummary: draft.suggestedSummary,
                  dataGaps: draft.dataGaps,
                }
              : null,
          }),
        });

        if (res.status === 401 || res.status === 403) {
          navigate('/login');
          return;
        }

        if (!res.ok) {
          const errorBody = await res.json().catch(() => ({}));
          throw new Error(errorBody.error || `서버 오류: HTTP ${res.status}`);
        }

        const data = await res.json();

        const assistantMessage = {
          id: makeId(),
          role: 'assistant',
          content: data.reply ?? data.message ?? '응답을 받았습니다.',
          timestamp: Date.now(),
          diff: data.diff ?? null,
          diffStatus: data.diff ? 'pending' : null,
          jsonDiff: data.jsonDiff ?? null,
          jsonDiffStatus: data.jsonDiff ? 'pending' : null,
          // Sub-AC 4-2: 백엔드 정규화된 citations 우선, 폴백으로 rankedEvidence
          citations:
            Array.isArray(data.citations) && data.citations.length > 0
              ? data.citations
              : Array.isArray(data.rankedEvidence) && data.rankedEvidence.length > 0
                ? data.rankedEvidence
                : null,
          applyIntent: data.applyIntent ?? null,
        };
        setMessages((prev) => [...prev, assistantMessage]);
      } catch (err) {
        const errorMessage = {
          id: makeId(),
          role: 'assistant',
          content: `오류가 발생했습니다: ${err.message}`,
          timestamp: Date.now(),
          error: true,
        };
        setMessages((prev) => [...prev, errorMessage]);
      } finally {
        setLoading(false);
      }
    },
    [loading, messages, sessionId, draft]
  );

  return {
    // 초안
    draft,
    insightDraft,
    draftStatus,
    draftError,
    draftRetry,

    // 메시지
    messages,
    setMessages,

    // 채팅 API
    sendMessage,
    loading,

    // 세션
    sessionId,

    // 이력서 상태
    initialResume,
    currentResume,
    refreshResume,
    approvedCount,
  };
}
